version: "3.8"

services:
  jekyll:
    # 1) On construit l’image locale décrite dans le Dockerfile
    build: .
    container_name: jekyll-dev

    # 2) Variables d’environnement
    environment:
      - JEKYLL_ENV=development        # mode dev (pas de minification)
      - TZ=Europe/Paris               # fuseau horaire interne du conteneur

    # 3) Volumes
    volumes:
      # code source monté en lecture/écriture
      - .:/srv/jekyll:delegated
      # ==> pas de volume sur /usr/local/bundle : on garde les gems dans l’image

    # 4) Ports (HTTP + livereload)
    ports:
      - "4000:4000"     # site dispo sur http://localhost:4000
      - "35729:35729"   # livereload

    # 5) Commande d’exécution
    command: >
      jekyll serve
      --watch
      --livereload
      --host=0.0.0.0
      --port=4000